
modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="apothecary"
version="1.0.0"
displayName="Apothecary"
authors="gobies"
description='''more potions!'''

[[dependencies.apothecary]]
modId= "forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.apothecary]]
modId= "minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"
