
modLoader="javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mixins]]
config = "apothecary.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]]
modId="apothecary"
version="1.5.0.6"
displayName="Apothecary"
authors="gobies"
description='''A potion expansion to liven up the alchemy experience in Minecraft!'''

[[dependencies.apothecary]]
modId="neoforge"
mandatory= true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.apothecary]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side= "BOTH"

[modproperties.apothecary]
configuredBackground="minecraft:textures/block/stone_bricks.png"
